### ISSUE TITLE
Improvement of 3D labeling tool

### ISSUE THREAD

**Issue by d-hayashi** [tier4/AutomanTools#10]
# Description
I am planning to make some PRs related to the following bug fixes and new features.
I will make PR for each item.

# Bug fixes
- [ ] Behavior of 3D labeling tool when resizing the window or moving frames (#11)

# New features
- [ ] Added an attribute 'object_id' to 3D Labels
- [ ] Load keymaps from a JSON file (keymaps are updated from the original version)
- [ ] Undo/Redo and Copy/Paste
- [ ] Duplicate labels
- [ ] Select multiple labels and move/copy/paste/duplicate/delete them at once
- [ ] Refactoring (prettier) labeling tool
- [ ] Resize boxes to the template size (useful when not the entire body of a vehicle is visible)

**Comment by kan-bayashi** [comment]
@eratostennis ping
