### ISSUE TITLE
"Label Min Size" not working properly

### ISSUE THREAD

**Issue by tsshimo** [tier4/AutomanTools#27]
**Describe the bug**
Custom label size (e.g. 30x30, 100x100) is not working properly in `2DBB` labeling screen.

**To Reproduce**
1. Create new project
2. Set classset and custom label min size
3. Label on the annotation screen
4. See label size bug

**Screenshots**
label size bug
![minSizeBug](https://user-images.githubusercontent.com/39268318/67738231-139f1b00-fa51-11e9-898f-97ac772c08ed.gif)

I was created this klassset using custom `Label Min Size`
![image](https://user-images.githubusercontent.com/39268318/67738279-59f47a00-fa51-11e9-85d6-ca55db544fba.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: chrome 77.0.3865.120 (64bit)

**Comment by Monjisan** [comment]
This is frontend bugs by casting form variable.
It is fixed in some bug fixes.
