### ISSUE TITLE
SET HEIGHT applies to all labels

### ISSUE THREAD

**Issue by tsshimo** [tier4/AutomanTools#34]
**Describe the bug**
Using `SET HEIGHT`, to change the height of all labels

**To Reproduce**
1. Open 3D labeling
2. Create 2 or more labels in the same frame
3. Push `SET HEIGHT` button

**Expected behavior**
Only the selected label changes size

**Screenshots**
![set_height_bug](https://user-images.githubusercontent.com/39268318/69292212-de00e280-0c48-11ea-96d3-36a5817f792b.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: chrome 77.0.3865.120 (64bit)
 - develop branch (https://github.com/tier4/AutomanTools/commit/83faf144eb89f73c4ffbdf5267bd71605474d270)

**Comment by Monjisan** [comment]
Fixed at #47.
