### ISSUE TITLE
cannnot upload big size rosbag

### ISSUE THREAD

**Issue by hayato-m126** [tier4/AutomanTools#71]
**Describe the bug**
I tried to upload rosbag size 8.0GB, then upload process not starts, nothing happens.
Is there limitaiton of rosbag size?

**To Reproduce**
Raw -> upload -> select bag

**Expected behavior**
If rosbag size is over limitation, alert message. 

**Desktop (please complete the following information):**
 - Environment [Vagrant(VirtualBox)]
 - Automan Version [master]

**Comment by eratostennis** [comment]
Thank you for the feedback.
This problem is OK now, so I close the issue.
